"""empty message

Revision ID: 64168afd925b
Revises: a2a7e42c816b
Create Date: 2024-11-07 18:39:29.142423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64168afd925b'
down_revision = 'a2a7e42c816b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
